### ISSUE TITLE
[issue][linux] Logger is not defined 

### ISSUE THREAD

**Issue by HadrienCazes** [09wattry/vim-adventures#4]
Hello,

I had a slight issue while running `./vim-adventures` on my Linux and I can't seem to fix it myself since I don't know much about Web Development at all !
Here's the log on my terminal:
![image](https://user-images.githubusercontent.com/22281895/79991632-cefdb500-84b2-11ea-9fa7-0032dfb061f6.png)

I tried to add a Logger variable but it doesn't seem to do much...

**Comment by 09wattry** [comment]
@HadrienCazes thanks for reporting this I will investigate this when I have time.

**Comment by 09wattry** [comment]
@HadrienCazes can you pull the latest version, follow the updated readme, and let me know how it goes?

**Comment by 09wattry** [comment]
I have added a CICD pipeline to allow you to just pull the binaries for your OS. You'll still need to add a .env file and created a saved directory then point your .env file to the location. I will update the README.

**Comment by HadrienCazes** [comment]
Hello ! It's working great now ! Thank you so much :+1:

**Comment by 09wattry** [comment]
@HadrienCazes you're welcome.
