### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by slmg** [09wattry/vim-adventures#5]
Thanks for creating this repo, impressive reverse engineering!

I ran it locally using Docker, I think it could be good to add this to your repo, and pushing the resulting image to Dockerhub would make it even easier to run.

In a nutshell:

Build

```Dockerfile
# Dockerfile
FROM node
RUN npm install https://github.com/09wattry/vim-adventures-rev.git
CMD [ "./root/vim-adventures/vim-adventures" ]
```

```sh
docker build -t vim-adventures:latest .
```

Run locally

```sh
docker container run -p 127.0.0.1:8080:80 vim-adventures
```

**Comment by 09wattry** [comment]
@slmg thanks for the suggestion! I didn't go with Docker since it may add another layer of learning for users that just want to play it. However, Docker is fun so thanks for the suggestion!

**Comment by slmg** [comment]
Personally, as I already used Docker I find it's much easier to copy and paste some `docker run ...` command than configure and build from a node environment. Leave it up to the user to use Docker or not.

Happy to give you a hand on this if you wish?

**Comment by 09wattry** [comment]
@slmg https://github.com/09wattry/vim-adventures/pull/7 I have put in this pull request. Take a look over it and let me know if you have any objections to how I've added Docker. Thanks.

**Comment by slmg** [comment]
I just created #17  to complement your previous PR.
